name: Patreon webhook test

on:
  workflow_dispatch:
# Allows external webhook trigger
# https://kontent.ai/blog/how-to-trigger-github-action-using-webhook-with-no-code/
  repository_dispatch:
    types:
      - webhook

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}